### ISSUE TITLE
Newbie quest not detecting item

### ISSUE THREAD

**Issue by ZeroLyfe** [SelenaQuartzRose/MineScape-Issues#2]
In the Newbie quest line the quest for crafting the Redstone energy fluxduct does not detect that the item has been crafted. It looks like you selected the filled redstone fluxduct for the crafting part of the quest instead of the empty fluxduct. I was able to complete the quest after editing the book and crafting 12 more ducts.

**Comment by SelenaQuartzRose** [comment]
Thanks - will fix!

**Comment by SelenaQuartzRose** [comment]
Fixed in version 1.6
