### ISSUE TITLE
Seared Brick quest

### ISSUE THREAD

**Issue by LadyGrelka** [SelenaQuartzRose/MineScape-Issues#3]
I had to start a new game, and when I get to the Seared Brick quest I have almost two stacks of brick and it is still not detecting that I have them, I have tried manual detect but that as well does not work.

**Comment by SelenaQuartzRose** [comment]
Hmmm, interesting. Are they the black seared bricks made out of clay/sand/gravel grout?
I will try switching this item detection to another mode (fuzzy or ore dictionary) and see if it fixes it.

**Comment by LadyGrelka** [comment]
Made grout from clay blocks and then turned said grout to seared bricks.

**Comment by SelenaQuartzRose** [comment]
OK. I will use MineTweaker to try to fix the issue. I am not sure what the problem could be, though. But I hope this will fix your issue.
Something else you could try is to throw all of the bricks on the ground at once and pick them back up.

**Comment by LadyGrelka** [comment]
Throwing them on the ground at once was the first thing I tried when it did not work. lol

**Comment by SelenaQuartzRose** [comment]
Ha. OK. Well I have made some major changes for version 1.6a that should have the lovely side-effect of fixing your issue.
Quick Question: When you hover over your seared bricks they have a damage value of 2, correct? 
Or if you hold them in your hand and type /minetweaker hand, does it say they are TConstruct:materials:2?
Just trying to troubleshoot what the exact issue is here. That item should work for the quest, but if it doesn't, it totally should in version 1.6a. 

Please let me know as soon as you update if it has been fixed so I can close the issue.
Thanks!! <3

**Comment by LadyGrelka** [comment]
Update did not fix the issue.  Using the command does give me TConstruct:materials:2

**Comment by SelenaQuartzRose** [comment]
Bizarre. Can you please take a screenshot of the quest's page in the quest log and upload it here?

**Comment by SelenaQuartzRose** [comment]
The weird thing is I just tried it in-game and it worked for me with no problems. =/ I think your quest data must have gotten bugged somehow. 
I would use "/hqm edit" to obtain the Op quest log. (You will probably have to "Open to Lan" and select "Allow cheats: ON" to use this command)
Then simply shift-click on the quest and presto, it should be completed.

**Comment by LadyGrelka** [comment]
I will do that when I get home thanks.

**Comment by LadyGrelka** [comment]
Did the hpm command and that worked and no other problems with quests so far.

**Comment by SelenaQuartzRose** [comment]
Hopefully no one else will have this issue, but if they do I will re-investigate. For now I believe it was a temporary bug with HQM.
