### ISSUE TITLE
Spawns in a void with a single grass block below me

### ISSUE THREAD

**Issue by ghost** [SelenaQuartzRose/MineScape-Issues#6]
Basically what the title says, I'm just spawning in a void with a grass block below me.

**Comment by SelenaQuartzRose** [comment]
That's pretty weird. Try a new world; if that doesn't work, remove and re-install the modpack. If all else fails, get the client log and post it so I can see what, if any, mod is causing the error.

**Comment by SelenaQuartzRose** [comment]
Creating a new world save fixed the issue. Likely cause: data corruption of world. Closed for now.
